### PR TITLE
some work on ThreadCreation

### PR DESCRIPTION
**Pull request by digitalist**

### CODE REVIEW

**Comment by digitalist** [comment]
how are we doing with translations?

**Comment by RainerGrimm** [comment]
> how are we doing with translations?
> Honestly, I have no idea. What are your plans? In case we start with the
> Russia posts at www.ModernesCpp.com, they have to be in sync with the
> English posts. So that a great burden on you. Maybe you look for a few
> people, which helps you to translate the posts. In case you do it on a
> separate side, you can step forward in your pace. I have no  problem
> with this. You should only mention me on the posts.
> 
> On Tue, Apr 26, 2016 at 11:03 PM, Rainer Grimm notifications@github.com
> wrote:
> 
> > Merged #4 https://github.com/RainerGrimm/ModernesCpp/pull/4.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/RainerGrimm/ModernesCpp/pull/4#event-642016650
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/RainerGrimm/ModernesCpp/pull/4#issuecomment-215557990

## 

Rainer Grimm  
Modernes C++: http://grimm-jaud.de/index.php/blog

**Comment by digitalist** [comment]
ah, I, misspelled. I was talking about total process of proofreading.
Translating to Russian is much easier than proof-reading English )
I saw your first english article, though I'll send some pull request today,
I hope (I've upgraded to ubuntu 16.04 and broken my boost libs somwhere,
trying to fix it)

**Comment by digitalist** [comment]
(proofreading through threads, part 4), some notices you could find useful
in the future:
when you say 'per copy' right translation is 'by value'
when you say 'invocation' right translation is 'calling', invocation is
something like 'summoning, calling a daemon with a spell and a pentagram',
'calling' is a standard term

**Comment by digitalist** [comment]
what does this phrase mean?

> After Adam Riese (a German proverb), the result must be 1000 +  6 \* 5 =
> 1030.
> I googled and found https://en.wikipedia.org/wiki/Adam_Ries (Riese/Ries)
> proverb is (is a simple and concrete saying
> https://en.wikipedia.org/wiki/Saying) from
> https://en.wikipedia.org/wiki/Proverb
> maybe this phrase should be something like this:
> As Adam Riese predicts (says, according to ... ), the result must be 1000
> -  6 \* 5 = 1030.

**Comment by digitalist** [comment]
though maybe there is a German proverb mentioning Adam Riese, I never heard
of proverbs about scientists, but I'm Russian, we put scientists in jail
usually. It could be good example of culture differences

**Comment by RainerGrimm** [comment]
He Alexey,

Am 03.05.2016 um 02:26 schrieb Alexey Elymanov:

**Comment by digitalist** [comment]
thanks, googled some more. It seems 'according to Adam Riese' will be
preferrable variant of translation.

**Comment by digitalist** [comment]
though I didn't understand some of your comments to my pull request -
'prefer simpler version' and 'prefer this version'?

**Comment by RainerGrimm** [comment]
Sorry,
about the irritation. That was due to my fight with the different 
GUI-Clients of git. Now I switched to the command line and the whole git 
stuff makes sense. With the GUI, I can only comment your changes but 
make no merges, commits, pushes. Strange!

Regards,
Rainer

Am 03.05.2016 um 15:51 schrieb Alexey Elymanov:

**Comment by digitalist** [comment]
opensource git gui is so crappy (sorry for my french), but CLion/PhpStorm
 merge/diff is very useful. Haven't see better diff (meld, vim etc.)

**Comment by digitalist** [comment]
*opensource git GUIs are all so crappy.

also, not irritation, but inconvinience (something bothering) /
misunderstanding (like, we couldn't understand each other)

**Comment by RainerGrimm** [comment]
I'm used to hg on the commandline. So I will stick for the next time 
with the command line. Maybe, I'm not the fastestet one with the gui, 
but at least, I see, what I do. With the GUI, i had no idea.

Am 03.05.2016 um 21:22 schrieb Alexey Elymanov:

**Comment by digitalist** [comment]
my persona cheat-sheet

git status
git add . # (add all files)
git add somefile

git commit -m "message"
git commit --amend -m "rewrite previous commit"

git clean -f -d #remove all new/untracked files

git remote -v #list all places from which you can pull or push to

**Comment by digitalist** [comment]
git fetch #update from default origin
git fetch SomeRemoteName #update from another
git pull -s ours #pull but don't rewrite local version
git reset --hard origin/master #reset all working tree and files to remote
version

seems these are most used commands for me

**Comment by RainerGrimm** [comment]
Thanks. I'm used to prcs, rcs, cvs, subversion and hg. But not to GUIS. 
I implemented command line tool for a product, based on hg. I introduced 
tortioise to my company and gave talks about the tool. So I know the 
concepts. With the GUI, I only saw a lot of frames without content. 
There was a publish button, where I looked for commit and push. There 
was no merge button. No button to partially apply a merge. After 2 hours 
and 3 GUI Clients for git, I gave up.
But, now I'm fine. I have the power of the command line with the git 
Shell windows and editor to make my canges.

Am 03.05.2016 um 21:38 schrieb Alexey Elymanov:

**Comment by digitalist** [comment]
> I'm used to prcs, rcs, cvs, subversion and hg.
> you did a long, hard way from hell.

**Comment by RainerGrimm** [comment]
Hi,
I will publish the source code in a separate repo. Something like 
ModernesCppSource.
My idea is it, to use a flat hierachy and copy all files in that hierachy.
So each the source code in the example  gets a additional line // 
myThreading.cpp. myThreading.cpp will be the name in the flat repo.
@Alexey: You have to add 2 to each line number in your translated posts. 
So the numbers will be in synch.

Regards,
Rainer

Am 03.05.2016 um 21:51 schrieb Alexey Elymanov:

**Comment by digitalist** [comment]
could you please show an example? what lines do I have to add? can it be done through simple merging?

**Comment by RainerGrimm** [comment]
Hi,
no be deal for you.
I only add to line to each file. I will do it tomorrow.
So instead of a file like:
1 # include <iostream>
2 # <string>

it will start with.
1 // nameOfTheFile.cpp
2
3 # include <iostream>
4 # <string>

So you have to add only 2 to each reference of the line numbers is the
post.
Tomorrow, I will make that stuff. So each reader knows form the name in
the head of the file (nameOfTheFile.cpp), which file he has to use.

Rainer

> could you please show an example? what lines do I have to add? can it be
> done through simple merging?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/RainerGrimm/ModernesCpp/pull/4#issuecomment-216986529

## 

Rainer Grimm
Modernes C++: http://grimm-jaud.de/index.php/blog

**Pull request merged**
